// <auto-generated />
using System;
using BanSach.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BanSach.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BanSach.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaCT"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MaDH")
                        .HasColumnType("integer");

                    b.Property<int>("MaSach")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("MaCT");

                    b.HasIndex("MaDH");

                    b.HasIndex("MaSach");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("BanSach.Models.ChuDe", b =>
                {
                    b.Property<int>("MaCD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaCD"));

                    b.Property<string>("TenChuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MaCD");

                    b.ToTable("ChuDes");
                });

            modelBuilder.Entity("BanSach.Models.DiaChi", b =>
                {
                    b.Property<int>("MaDC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDC"));

                    b.Property<string>("DiaChiChiTiet")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("MaKH")
                        .HasColumnType("integer");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("boolean");

                    b.HasKey("MaDC");

                    b.HasIndex("MaKH");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("BanSach.Models.DonHang", b =>
                {
                    b.Property<int>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDH"));

                    b.Property<string>("DiaChiGiao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MaDC")
                        .HasColumnType("integer");

                    b.Property<int>("MaKH")
                        .HasColumnType("integer");

                    b.Property<int?>("MaSDT")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SoDienThoaiGiao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("MaDH");

                    b.HasIndex("MaDC");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaSDT");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("BanSach.Models.GiaoHang", b =>
                {
                    b.Property<int>("MaGH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaGH"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MaDH")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("MaGH");

                    b.HasIndex("MaDH")
                        .IsUnique();

                    b.ToTable("GiaoHangs");
                });

            modelBuilder.Entity("BanSach.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKH"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("MaTK")
                        .HasColumnType("integer");

                    b.HasKey("MaKH");

                    b.HasIndex("MaTK")
                        .IsUnique();

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("BanSach.Models.NhaXuatBan", b =>
                {
                    b.Property<int>("MaNXB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNXB"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TenNXB")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MaNXB");

                    b.ToTable("NhaXuatBans");
                });

            modelBuilder.Entity("BanSach.Models.NhomSach", b =>
                {
                    b.Property<int>("MaNhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNhom"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("integer");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.HasKey("MaNhom");

                    b.ToTable("NhomSachs");
                });

            modelBuilder.Entity("BanSach.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSach"));

                    b.Property<string>("AnhBia")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MaCD")
                        .HasColumnType("integer");

                    b.Property<int>("MaNXB")
                        .HasColumnType("integer");

                    b.Property<int>("MaNhom")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<int?>("NamXB")
                        .HasColumnType("integer");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("boolean");

                    b.Property<bool>("SachMoi")
                        .HasColumnType("boolean");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("integer");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("MaSach");

                    b.HasIndex("MaCD");

                    b.HasIndex("MaNXB");

                    b.HasIndex("MaNhom");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("BanSach.Models.SachTacGia", b =>
                {
                    b.Property<int>("MaSach")
                        .HasColumnType("integer");

                    b.Property<int>("MaTG")
                        .HasColumnType("integer");

                    b.HasKey("MaSach", "MaTG");

                    b.HasIndex("MaTG");

                    b.ToTable("SachTacGias");
                });

            modelBuilder.Entity("BanSach.Models.SoDienThoai", b =>
                {
                    b.Property<int>("MaSDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSDT"));

                    b.Property<int>("MaKH")
                        .HasColumnType("integer");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("boolean");

                    b.Property<string>("SoDT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaSDT");

                    b.HasIndex("MaKH");

                    b.ToTable("SoDienThoais");
                });

            modelBuilder.Entity("BanSach.Models.TacGia", b =>
                {
                    b.Property<int>("MaTG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTG"));

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TieuSu")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("MaTG");

                    b.ToTable("TacGias");
                });

            modelBuilder.Entity("BanSach.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTK"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ResetTokenHetHan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("boolean");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaTK");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("BanSach.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("BanSach.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanSach.Models.Sach", "Sach")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("BanSach.Models.DiaChi", b =>
                {
                    b.HasOne("BanSach.Models.KhachHang", "KhachHang")
                        .WithMany("DiaChis")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BanSach.Models.DonHang", b =>
                {
                    b.HasOne("BanSach.Models.DiaChi", "DiaChi")
                        .WithMany()
                        .HasForeignKey("MaDC")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BanSach.Models.KhachHang", "KhachHang")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BanSach.Models.SoDienThoai", "SoDienThoai")
                        .WithMany()
                        .HasForeignKey("MaSDT")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiaChi");

                    b.Navigation("KhachHang");

                    b.Navigation("SoDienThoai");
                });

            modelBuilder.Entity("BanSach.Models.GiaoHang", b =>
                {
                    b.HasOne("BanSach.Models.DonHang", "DonHang")
                        .WithOne("GiaoHang")
                        .HasForeignKey("BanSach.Models.GiaoHang", "MaDH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("BanSach.Models.KhachHang", b =>
                {
                    b.HasOne("BanSach.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("BanSach.Models.KhachHang", "MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("BanSach.Models.Sach", b =>
                {
                    b.HasOne("BanSach.Models.ChuDe", "ChuDe")
                        .WithMany("Sachs")
                        .HasForeignKey("MaCD")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BanSach.Models.NhaXuatBan", "NhaXuatBan")
                        .WithMany("Sachs")
                        .HasForeignKey("MaNXB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BanSach.Models.NhomSach", "NhomSach")
                        .WithMany("Sachs")
                        .HasForeignKey("MaNhom")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChuDe");

                    b.Navigation("NhaXuatBan");

                    b.Navigation("NhomSach");
                });

            modelBuilder.Entity("BanSach.Models.SachTacGia", b =>
                {
                    b.HasOne("BanSach.Models.Sach", "Sach")
                        .WithMany("SachTacGias")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BanSach.Models.TacGia", "TacGia")
                        .WithMany("SachTacGias")
                        .HasForeignKey("MaTG")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sach");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("BanSach.Models.SoDienThoai", b =>
                {
                    b.HasOne("BanSach.Models.KhachHang", "KhachHang")
                        .WithMany("SoDienThoais")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("BanSach.Models.ChuDe", b =>
                {
                    b.Navigation("Sachs");
                });

            modelBuilder.Entity("BanSach.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("GiaoHang");
                });

            modelBuilder.Entity("BanSach.Models.KhachHang", b =>
                {
                    b.Navigation("DiaChis");

                    b.Navigation("DonHangs");

                    b.Navigation("SoDienThoais");
                });

            modelBuilder.Entity("BanSach.Models.NhaXuatBan", b =>
                {
                    b.Navigation("Sachs");
                });

            modelBuilder.Entity("BanSach.Models.NhomSach", b =>
                {
                    b.Navigation("Sachs");
                });

            modelBuilder.Entity("BanSach.Models.Sach", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("SachTacGias");
                });

            modelBuilder.Entity("BanSach.Models.TacGia", b =>
                {
                    b.Navigation("SachTacGias");
                });

            modelBuilder.Entity("BanSach.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");
                });
#pragma warning restore 612, 618
        }
    }
}
